// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eshopADN.Server.Data;

#nullable disable

namespace eshopADN.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eshopADN.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Libri",
                            Url = "libri"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Quadri, ritratti e stampe",
                            Url = "quadri"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Decorazioni",
                            Url = "decorazioni"
                        });
                });

            modelBuilder.Entity("eshopADN.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Descrizione = "La torre sull'oceano: Una strana, assurda magia lega le anime di Isaac e di Viola. Lui è un solitario, malinconico artista che riesce ad incantare chiunque ascolti le note della sua armonica. Lei è bellissima, fragile e porta sulle spalle una vita difficile. Nessuno dei due riesce a capire cosa sia quella strana sensazione che li pervade quando, casualmente, incrociano gli sguardi. Eppure la loro storia non si intreccia con la soave delicatezza che ci si aspetterebbe da una storia d'amore. Per loro, le cose sono complesse ed oscure. Presto si incontreranno, in una situazione agli antipodi del romanticismo. E le cose, come sempre, non andranno come ci aspettiamo.",
                            Featured = false,
                            ImagePath = "https://www.unilibro.it/cover/libro/9788868543259B.jpg",
                            IsAvailable = false,
                            Titolo = "La torre sull'oceano"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Descrizione = "Nicole ha trent'anni. Il mondo da tempo non è più quel luogo magico in cui credeva durante l'infanzia, tuttavia alla sua piccola Desirée, cinque anni, sua unica ragione di vita, vorrebbe mostrarlo così come lo ricorda. Ma il destino è beffardo e si prende gioco di lei, mandando all'aria ogni suo progetto, portandola a mettere in discussione ogni sua fede e costringendola ad affrontare quel segreto che si porta dentro e che, lentamente, la sta portando via.",
                            Featured = true,
                            ImagePath = "https://www.mondadoristore.it/img/Le-bastava-profumo-dell-erba-Nadia-Cristoni/ea978886628471/BL/BL/01/NZO/?tit=Le+bastava+il+profumo+dell%27erba&aut=Nadia+Cristoni",
                            IsAvailable = false,
                            Titolo = "Le bastava il profumo dell'erba"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Descrizione = "Si intravede Bologna in filigrana, e la sua armoniosa, serena provincia, attraverso la storia di Penelope, una donna che non vuole crescere. Aiutata dal suo aspetto fisico, che nasconde la sua vera età, dall'entusiasmo per la vita, e da un bisogno quasi selvaggio di libertà, può forse permettersi di essere un'eterna bambina, anche se traumi, sensi di inadeguatezza e continui conflitti emergono prepotenti dal suo passato. Per sopravvivere a questi, e sperare di trasformarsi da crisalide in farfalla, dovrà superare le prove che rendono emotivamente adulti: la sconfitta, l'abbandono, la solitudine, l'amore. Affronterà ciascuna sfida con il suo proprio stile, a dispetto dell'età, delle convenienze e dei giudizi della società, e forse alla fine troverà il suo modo di stare al mondo. Forse.",
                            Featured = false,
                            ImagePath = "https://www.artedinadia.it/wp-content/uploads/2023/05/64-copertina.jpg",
                            IsAvailable = false,
                            Titolo = "Forse"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Descrizione = "Una storia che si divide in due parti, dall’immediato dopoguerra agli inizi del 1970. La protagonista è Estelle, una diciannovenne in grado di comunicare con i morti e di farsi obbedire dal vento, elemento capace di purificare il peccato e trasformare la vita e la tristezza. Allevata in una una comunità gitana, inizierà un viaggio alla ricerca delle proprie origini. Creatura selvaggia e indomita, risorgerà sempre dalle sue ceneri grazie alla fede e alla forza che la contraddistinguono.\n\nUna vita fatta di conflitti, sofferenze e persecuzioni, quella di Estelle, personaggio emblematico e fuori dal tempo ma che, nel momento più difficile, saprà regalare forza e intuizione sufficienti per accettarsi e ritrovare la voglia di vivere.",
                            Featured = false,
                            ImagePath = "https://www.artedinadia.it/wp-content/uploads/2023/05/CopertinaLaReginadelVento-726x1024.jpg",
                            IsAvailable = false,
                            Titolo = "La regina del vento"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Descrizione = "Progettazione di ritratti su misure standard o personalizzate. Il ritratto è un'opera d'arte che rappresenta una persona o un gruppo di persone. Il ritratto può essere realizzato in diversi modi: pittura, disegno, fotografia, scultura, ecc. Il ritratto è un'opera d'arte che rappresenta una persona o un gruppo di persone. Il ritratto può essere realizzato in diversi modi: pittura, disegno, fotografia, scultura, ecc.",
                            Featured = true,
                            ImagePath = "https://www.artedinadia.it/wp-content/gallery/quadri/esercitazione-a-spatola.jpg",
                            IsAvailable = false,
                            Titolo = "Ritratto su commissione"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Descrizione = "Decorazioni su pareti, tessuti, mobili e oggetti. Soggetti e colori personalizzabili. Il ritratto è un'opera d'arte che rappresenta una persona o un gruppo di persone. Il ritratto può essere realizzato in diversi modi: pittura, disegno, fotografia, scultura, ecc. Il ritratto è un'opera d'arte che rappresenta una persona o un gruppo di persone. Il ritratto può essere realizzato in diversi modi: pittura, disegno, fotografia, scultura, ecc.",
                            Featured = true,
                            ImagePath = "https://www.artedinadia.it/wp-content/gallery/quadri/esercitazione-a-spatola.jpg",
                            IsAvailable = false,
                            Titolo = "Decorazione su commissione"
                        });
                });

            modelBuilder.Entity("eshopADN.Shared.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Libro Cartaceo"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ebook"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ritratto su commissione sm(30x40)"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Ritratto su commissione md(50x70)"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Ritratto su commissione lg(70x100)"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Dipinto su commissione sm(30x40)"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Dipinto su commissione md(50x70)"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Dipinto su commissione lg(70x100)"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Come da immagine"
                        });
                });

            modelBuilder.Entity("eshopADN.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 1,
                            OriginalPrice = 19.99m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 2,
                            OriginalPrice = 12.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 1,
                            OriginalPrice = 19.99m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 2,
                            OriginalPrice = 12.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 1,
                            OriginalPrice = 19.99m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 2,
                            OriginalPrice = 12.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 1,
                            OriginalPrice = 19.99m,
                            Price = 15.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 2,
                            OriginalPrice = 12.99m,
                            Price = 9.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 3,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 4,
                            OriginalPrice = 99.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 5,
                            OriginalPrice = 129.99m,
                            Price = 99.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 6,
                            OriginalPrice = 59.99m,
                            Price = 49.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 7,
                            OriginalPrice = 99.99m,
                            Price = 79.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 8,
                            OriginalPrice = 129.99m,
                            Price = 99.99m
                        });
                });

            modelBuilder.Entity("eshopADN.Shared.Product", b =>
                {
                    b.HasOne("eshopADN.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eshopADN.Shared.ProductVariant", b =>
                {
                    b.HasOne("eshopADN.Shared.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eshopADN.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("eshopADN.Shared.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
